### ISSUE TITLE
[SUGGESTION] Recipe toggles

### ISSUE THREAD

**Issue by Nachtflame** [Nater0097/Trinity#2]
Is there any chance you could setup a config for T/F toggles for your recipes? With no native methods for removing/modifying existing recipes, the ability to config them fore purposes of mod-pack customization would be amazing.  Thank you!

**Comment by OribiaDev** [comment]
So im confused about what your asking, do you want me to make a true/false toggle for recipes or to make the recipes easily configurable?

**Comment by Nachtflame** [comment]
As little as a the ability to toggle the native recipes off, without actually losing the registered items, would be awesome.
Datapacks make adding custom add recipes super simple, but they have no means of removing/modifying existing recipes.

**Comment by OribiaDev** [comment]
ohhh ok, im going to post an update on Friday and I will try to put that in for you.

**Comment by OribiaDev** [comment]
if you want a faster and easier way too enable them and disable them use this curseforge.com/minecraft/mc-mods/crafttweaker, the last time that I checked it still works in 1.13 and 1.14

**Comment by OribiaDev** [comment]
So I haven't found a way to do what your asking for 1.14 forge, I'm sorry but I suggest you use the mod above.

**Comment by Nachtflame** [comment]
Thank you for trying. And no, it (craft-tweaker for 1.12.2) doesn't work on current forge versions.
